<footer>
   <hr/>
   <p>
   <!--Image from https://www.sfcinemacity.com/showtime/movie/HO00000202 -->
   <span><img src="images/Searching.PNG" alt="searching" title="searching"/></span>
   <!--Image from https://www.sfcinemacity.com/showtime/movie/HO00000068 -->
   <span class="picFooter"><img src="images/thenun.PNG" alt="thenun" title="thenun"/></span>
   <!--Image from https://www.sfcinemacity.com/showtime/movie/HO00000155 -->
   <span><img src="images/pooh.PNG" alt="pooh" title="pooh"/></span>
   </p>
   <hr/>
   <p>Sunwit Petchoo</p>
   <hr/>
</footer>